# Generated by Django 6.0.1 on 2026-02-17 04:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0003_organizacao_cliente_organizacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("RECEITA", "Receita"), ("DESPESA", "Despesa")],
                        max_length=10,
                    ),
                ),
                ("grupo_dre", models.CharField(blank=True, max_length=120)),
                ("nao_entrar_dre", models.BooleanField(default=False)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BANCO", "Banco"),
                            ("CAIXA", "Caixa"),
                            ("CARTAO", "Cartão"),
                            ("GATEWAY", "Gateway"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RECEITA", "Receita"),
                            ("DESPESA", "Despesa"),
                            ("TRANSFERENCIA", "Transferência"),
                            ("INTERNO", "Registro Interno"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVISTO", "Previsto"),
                            ("PAGO", "Pago"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PREVISTO",
                        max_length=12,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("vencimento", models.DateField()),
                ("pagamento", models.DateField(blank=True, null=True)),
                ("competencia", models.CharField(help_text="YYYY-MM", max_length=7)),
                ("descricao", models.CharField(max_length=255)),
                ("processo_referencia", models.CharField(blank=True, max_length=120)),
                (
                    "anexo",
                    models.FileField(
                        blank=True, null=True, upload_to="financeiro/comprovantes/"
                    ),
                ),
                ("recorrente", models.BooleanField(default=False)),
                ("numero_parcela", models.PositiveIntegerField(default=1)),
                ("total_parcelas", models.PositiveIntegerField(default=1)),
                ("gateway_external_id", models.CharField(blank=True, max_length=120)),
                ("gateway_status", models.CharField(blank=True, max_length=60)),
                ("gateway_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="financeiro.categoriafinanceira",
                    ),
                ),
                (
                    "centro_custo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.centrocusto",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos",
                        to="financeiro.contafinanceira",
                    ),
                ),
                (
                    "conta_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_recebidas",
                        to="financeiro.contafinanceira",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lancamentos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
                (
                    "origem_recorrencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.lancamentofinanceiro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acao", models.CharField(max_length=32)),
                ("detalhes", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financeiro.lancamentofinanceiro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financeiro.unidade",
            ),
        ),
        migrations.CreateModel(
            name="FinancialAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("NONE", "Sem acesso"),
                            ("VIEWER", "Visualizador"),
                            ("FULL", "Completo"),
                        ],
                        default="FULL",
                        max_length=12,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("organizacao", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["organizacao", "status"], name="financeiro__organiz_8854e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["organizacao", "vencimento"],
                name="financeiro__organiz_499ade_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["organizacao", "competencia"],
                name="financeiro__organiz_23cc5a_idx",
            ),
        ),
    ]
