# Generated by Django 6.0.1 on 2026-02-19 17:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
        ("usuarios", "0003_organizacao_cliente_organizacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdiantamentoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processo_referencia", models.CharField(blank=True, max_length=120)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "saldo_disponivel",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtualizacaoMonetaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processo_referencia", models.CharField(max_length=120)),
                (
                    "indice",
                    models.CharField(
                        choices=[
                            ("IPCA", "IPCA"),
                            ("SELIC", "SELIC"),
                            ("IGPM", "IGPM"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "valor_original",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "valor_atualizado",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("taxa_aplicada", models.DecimalField(decimal_places=4, max_digits=8)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DespesaProcessual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processo_referencia", models.CharField(max_length=120)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TAXA", "Taxa judicial"),
                            ("COPIA", "Cópias"),
                            ("TRANSPORTE", "Transporte"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=16,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reembolsavel", models.BooleanField(default=True)),
                (
                    "status_reembolso",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("FATURADA", "Faturada"),
                            ("REEMBOLSADA", "Reembolsada"),
                        ],
                        default="PENDENTE",
                        max_length=12,
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(
                        blank=True, null=True, upload_to="financeiro/despesas/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adiantamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.adiantamentocliente",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaturaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processo_referencia", models.CharField(blank=True, max_length=120)),
                ("descricao", models.CharField(max_length=255)),
                ("vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGA", "Paga"),
                            ("ATRASADA", "Atrasada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE",
                        max_length=12,
                    ),
                ),
                (
                    "meio_pagamento",
                    models.CharField(
                        choices=[
                            ("BOLETO", "Boleto"),
                            ("PIX", "Pix dinâmico"),
                            ("CARTAO", "Cartão de crédito"),
                        ],
                        default="PIX",
                        max_length=10,
                    ),
                ),
                ("incluir_honorarios", models.BooleanField(default=False)),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("linha_digitavel", models.CharField(blank=True, max_length=120)),
                ("pix_qr_code", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Honorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processo_referencia", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PRO_LABORE", "Pró-labore"),
                            ("EXITO", "Êxito (ad exitum)"),
                            ("SUCUMBENCIA", "Sucumbência"),
                            ("MENSAL", "Mensal (retainer)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=255)),
                (
                    "valor_contratado",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "percentual_exito",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "valor_causa",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("total_parcelas", models.PositiveIntegerField(default=1)),
                ("recorrente_mensal", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("ATIVO", "Ativo"),
                            ("ENCERRADO", "Encerrado"),
                        ],
                        default="ATIVO",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaturaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("HONORARIO", "Honorário"), ("DESPESA", "Despesa")],
                        max_length=12,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.despesaprocessual",
                    ),
                ),
                (
                    "fatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="financeiro.faturafinanceira",
                    ),
                ),
                (
                    "honorario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.honorario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoAdiantamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CREDITO", "Crédito"),
                            ("USO", "Uso em despesa"),
                            ("ESTORNO", "Estorno"),
                        ],
                        max_length=10,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("observacao", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adiantamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="financeiro.adiantamentocliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "despesa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.despesaprocessual",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SplitPagamentoRegra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_parceiro", models.CharField(max_length=120)),
                ("percentual", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeTrackingFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processo_referencia", models.CharField(max_length=120)),
                ("descricao", models.CharField(max_length=255)),
                ("horas", models.DecimalField(decimal_places=2, max_digits=8)),
                ("valor_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                ("faturado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.organizacao",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="honorario",
            index=models.Index(
                fields=["organizacao", "cliente", "processo_referencia"],
                name="financeiro__organiz_f7a0e5_idx",
            ),
        ),
    ]
