# Generated by Django 6.0.1 on 2026-02-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_adiantamentocliente_atualizacaomonetaria_and_more"),
    ]

    operations = []
