# Generated by Django 6.0.1 on 2026-02-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_adiantamentocliente_atualizacaomonetaria_and_more'),
        ('financeiro', '0010_financeiro_juridico_base'),
    ]

    operations = [
    ]
